build_atomic:
  image: registry.gitlab.com/gbraad/fedora:24
  services:
    - docker:dind
  script:
    - dnf install -y make git python libffi-devel python-devel libselinux-python ostree-devel python-gobject-base pylint golang-github-cpuguy83-go-md2man redhat-rpm-config gcc PyYAML python-dbus python-docker-py rpm-python docker skopeo python-slip-dbus gcc-go python3-pylint python3-dbus python3-slip-dbus python3-docker-py python3-gobject-base python3-dateutil python2-dateutil python2-coverage
    - pip install python-dateutil xattr
    - git clone https://github.com/projectatomic/atomic.git atomic --depth 1 -b master
    - cd atomic
    - make
    - make install
  only:
    - master
  when: manual
